pipeline {
  agent any

stages {
  stage("Initial cleanup") {
    steps {
      dir("${WORKSPACE}") {
          deleteDir()
      } 
    }
  }

 stage('Build') {
  steps{
  script {
   sh 'echo "Building Stage"'
    }
  }
 }

}