pipeline {
    agent any

  stages {
    stage("Initial cleanup") {
      steps {
       dir("${WORKSPACE}") {
        deleteDir()
        }
      }
    }
  
  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

stages {
    stage('Package') {
      steps {
        script {
          sh 'echo "Packaging App"'
        }
      }
    }

stages {
    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploying to Dev"'
        }
      }
    }

stages {
    stage("cleanup") {
      steps {
       cleanWs()
        
        }
      }
    }

  }